name: Check Cache

on:
  workflow_call:
    inputs:
      os: # This is the os from the matrix
        required: true
        type: string
      arch: # This is the arch from the matrix
        required: false
        type: string
      build-deps-only:
        required: false
        type: boolean
      target_os: # New input for filtering
        required: false
        type: string
        default: "all"
      target_mac_arch: # New input for macOS arch filtering
        required: false
        type: string
        default: "all"

jobs:
  check_cache: # determines if there is a cache and outputs variables used in caching process
    name: Check Cache
    runs-on: ${{ inputs.os }}
    if: |
      (inputs.target_os == 'all' || inputs.target_os == inputs.os) &&
      (
        !startsWith(inputs.os, 'macos-') ||
        (inputs.target_mac_arch == 'all' || inputs.target_mac_arch == inputs.arch)
      )
    outputs:
      cache-key: ${{ steps.set_outputs.outputs.cache-key }}
      cache-path: ${{ steps.set_outputs.outputs.cache-path }}
      valid-cache: ${{ steps.cache_deps.outputs.cache-hit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: set outputs
        id: set_outputs
        env:
          is_macos: ${{ startsWith(inputs.os, 'macos-') }}
          underscore-arch: ${{ env.is_macos && '_' || ''}}${{ env.is_macos && inputs.arch || '' }}
          dash-arch: ${{ env.is_macos && '-' || ''}}${{ env.is_macos && inputs.arch || '' }}
          dep-folder-name: ${{ (inputs.os == 'windows-latest' || env.is_macos) && 'BambuStudio_dep' || 'destdir' }}
          output-cmd: ${{ inputs.os == 'windows-latest' && '$env:GITHUB_OUTPUT' || '"$GITHUB_OUTPUT"'}}
        run: |
          echo "is_macos_resolved=${{ env.is_macos }}" # Debugging line
          echo cache-key=${{ inputs.os }}${{ env.dash-arch }}-cache-bambustudio_deps-build-${{ hashFiles('deps/**') }} >> ${{ env.output-cmd }}
          echo cache-path=${{ github.workspace }}/deps/build${{ env.underscore-arch }}/${{ env.dep-folder-name }}${{ env.underscore-arch }} >> ${{ env.output-cmd }}

      - name: load cache
        id: cache_deps
        uses: actions/cache@v4
        with:
          path: ${{ steps.set_outputs.outputs.cache-path }}
          key: ${{ steps.set_outputs.outputs.cache-key }}
          lookup-only: true

  build_deps: # call next step
    name: Build Deps
    needs: [check_cache]
    # This job should only run if check_cache decided to run and produce outputs.
    # If check_cache is skipped due to its 'if' condition, its outputs might not be available.
    # So, we use the same condition here. An alternative is to rely on needs.check_cache.result != 'skipped'
    if: |
      (inputs.target_os == 'all' || inputs.target_os == inputs.os) &&
      (
        !startsWith(inputs.os, 'macos-') ||
        (inputs.target_mac_arch == 'all' || inputs.target_mac_arch == inputs.arch)
      )
    uses: ./.github/workflows/build_deps.yml
    with:
      cache-key: ${{ needs.check_cache.outputs.cache-key }}
      cache-path: ${{ needs.check_cache.outputs.cache-path }}
      valid-cache: ${{ needs.check_cache.outputs.valid-cache == 'true' }}
      os: ${{ inputs.os }}
      arch: ${{ inputs.arch }}
      build-deps-only: ${{ inputs.build-deps-only }}
      # target_os and target_mac_arch are NOT passed to build_deps.yml
      # build_deps.yml and build_bambu.yml will run unconditionally if called.
    secrets: inherit
