name: Build all

on:
  push:
    branches:
      - main
    paths:
      - "deps/**"
      - "src/**"
      - "**/CMakeLists.txt"
      - "version.inc"
      - "bbl/**"
      - "resources/**"
      - ".github/workflows/build_*.yml"

  pull_request:
    branches:
      - master
    paths:
      - "deps/**"
      - "src/**"
      - "**/CMakeLists.txt"
      - "version.inc"
      - ".github/workflows/build_*.yml"
      - "BuildLinux.sh"
      - "build_win.bat"

  workflow_dispatch: # manual dispatch
    inputs:
      build-deps-only:
        description: "Only build dependencies (bypasses caching)"
        type: boolean
        default: false
      target_os:
        description: "Specify target OS (all, ubuntu-20.04, ubuntu-24.04, windows-latest, macos-13, macos-latest)"
        type: choice
        options:
          - all
          - ubuntu-20.04
          - ubuntu-24.04
          - windows-latest
          - macos-13
          - macos-latest
        default: "all"
      target_mac_arch:
        description: "Specify target architecture for macOS (all, x86_64, arm64). Default is all."
        type: choice
        options:
          - all
          - x86_64
          - arm64
        default: "all"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_job:
    name: Build Matrix Target
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            arch: "x86_64"
          - os: windows-latest
            arch: "x64"
          - os: macos-13
            arch: "x86_64"
          - os: macos-latest
            arch: "arm64"
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      build-deps-only: ${{ inputs.build-deps-only || false }}
      target_os: ${{ inputs.target_os }}
      target_mac_arch: ${{ inputs.target_mac_arch }}
    secrets: inherit
