name: Build Self-Hosted

on:
  push:
    branches:
     - main
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - 'bbl/**'
     - 'resources/**'
     - ".github/workflows/build_*.yml"

  pull_request:
    branches:
     - master
    paths:
     - 'deps/**'
     - 'src/**'
     - '**/CMakeLists.txt'
     - 'version.inc'
     - ".github/workflows/build_*.yml"
     - 'BuildLinux.sh'
     - 'build_win.bat'
    
  workflow_dispatch: # manual dispatch
      inputs:
        build-deps-only:
            description: 'Only build dependencies (bypasses caching)'
            type: boolean
            default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_self_hosted:
    name: Build Self-Hosted macOS 15
    runs-on: self-hosted
    env:
      date:
    steps:
      # Setup the environment
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Get the date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      # Free disk space
      - name: Free disk space
        run: |
          df -h
          sudo find /Applications -maxdepth 1 -type d -name "Xcode_*.app" ! -name "Xcode_15.4.app" -exec rm -rf {} +
          sudo rm -rf ~/Library/Developer/CoreSimulator/Caches/*
          df -h

      # Build Dependencies
      - name: Build dependencies
        working-directory: ${{ github.workspace }}
        run: |
            brew install automake texinfo nasm yasm x264
            brew uninstall --ignore-dependencies zstd
            ./BuildMac.sh -d -x -a universal -t 10.15 -1
            for arch in arm64 x86_64; do
                (cd "${{ github.workspace }}/deps/build/${arch}" && \
                find . -mindepth 1 -maxdepth 1 ! -name 'BambuStudio_deps' -exec rm -rf {} +)
            done
            brew install zstd

      # Pack dependencies
      - name: Pack dependencies
        working-directory: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}/deps
          tar -zcvf "BambuStudio_dep_mac_universal_$(date +"%Y%m%d").tar.gz" build

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BambuStudio_dep_mac_universal_${{ env.date }}
          path: ${{ github.workspace }}/deps/BambuStudio_dep_mac_universal*.tar.gz

      # Clean artifacts
      - name: Clean artifacts
        working-directory: ${{ github.workspace }}
        run: rm -rf ${{ github.workspace }}/deps/build/BambuStudio_dep_mac_universal*.tar.gz

      # Build BambuStudio (if not deps-only)
      - name: Build BambuStudio
        if: ${{ !cancelled() && !inputs.build-deps-only }}
        working-directory: ${{ github.workspace }}
        run: |
            mkdir -p build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make -j$(nproc)
